version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
      - "5051:443"
    depends_on:
      - postgres



  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
     
    ports:
      - "1025:1025"
      - "8025:8025"
    
    volumes:
      - mailhog:/var/lib/mailhog


  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-stck:/var/lib/redis-stack
    environment:
      - REDIS_ARGS=--save 900 1
  
  rabbbitmq:
    image: rabbitmq:3.8-management
     
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      
volumes:
  postgres:
  mailhog:
  redis-stck:
  rabbitmq-data: