version: "3.9"

volumes:
  kong_data: {}
  js_plugins: {}

networks:
  kong-net:
    name: kong-net
    driver: bridge

services:
  kong-database:
    image: postgres:9.6
    container_name: kong-postgres
    restart: on-failure
    networks:
      - kong-net
    volumes:
      - kong_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong", "-d", "kong"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  kong-migration:
    image: kong:latest
    container_name: kong-migration
    command: kong migrations bootstrap
    networks:
      - kong-net
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    depends_on:
      kong-database:
        condition: service_healthy

  kong:
    image: kong:latest
    container_name: kong-gateway
    restart: on-failure
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PLUGINS: bundled,clacks
      KONG_PLUGINSERVER_NAMES: js
      KONG_PLUGINSERVER_JS_SOCKET: /usr/local/kong/js_pluginserver.sock
      KONG_PLUGINSERVER_JS_START_CMD: /usr/local/bin/kong-js-pluginserver -v --plugins-directory /usr/local/kong/js-plugins
      KONG_PLUGINSERVER_JS_QUERY_CMD: /usr/local/bin/kong-js-pluginserver --plugins-directory /usr/local/kong/js-plugins --dump-all-plugins
    volumes:
      - js_plugins:/usr/local/kong/js-plugins
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8002:8002"
      - "8444:8444"
    depends_on:
      kong-migration:
        condition: service_completed_successfully
      kong-database:
        condition: service_healthy

  js-plugin-server:
    image: node:16
    container_name: kong-js-plugin-server
    restart: on-failure
    networks:
      - kong-net
    volumes:
      - js_plugins:/usr/local/kong/js-plugins
    command: >
      /bin/sh -c "
        npm install -g kong-pdk &&
        kong-js-pluginserver -v --plugins-directory /usr/local/kong/js-plugins
      "
    depends_on:
      kong:
        condition: service_started

  init-js-plugin:
    image: node:16
    container_name: kong-js-plugin-init
    networks:
      - kong-net
    volumes:
      - js_plugins:/usr/local/kong/js-plugins
    command: >
      /bin/sh -c "
        npm install -g kong-pdk &&
        echo 'module.exports = {
          Plugin: class KongPlugin {
            constructor(config) {
              this.config = config;
            }
            async access(kong) {
              await kong.response.setHeader(\"X-Clacks-Overhead\", \"GNU Terry Pratchett\");
            }
          },
          Schema: [
            { message: { type: \"string\" } },
          ],
          Version: \"0.1.0\",
          Priority: 0
        }' > /usr/local/kong/js-plugins/clacks.js
      "
    depends_on:
      - js-plugin-server